image: php:7.4

pipelines:
  branches:
    production:
      - step:
          runs-on:
            - self.hosted
          name: Laravel Deployment Pipeline
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y rsync
